# .github/workflow/lighthouse-ci.yaml
name: Lighthouse
on:
  push:
    branches:
      - dev
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install && npm install -g @lhci/cli@0.7.x

      - name: Build site with Gatsby and run LHCI
        run: lhci autorun
        env:
          PRISMIC_API: ${{ secrets.PRISMIC_API }}
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_GITHUB_TOKEN=: ${{ secrets.LHCI_GITHUB_TOKEN }}