# .github/workflow/lighthouse-ci.yaml
name: Lighthouse
on:
  push:
    branches:
      - dev
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - env:
          PRISMIC_API: ${{ secrets.PRISMIC_API }}
      - run: npm install && npm install -g @lhci/cli@0.7.x
      - run: npm run build && npm run serve
      - run: lhci autorun